\set ON_ERROR_STOP on

-- Run as the Alibaba RDS privileged bootstrap account. Create both LOGIN roles
-- in the RDS console first so passwords never enter this file or shell history.
\if :{?migration_role}
\else
  \set migration_role wp_migration_owner
\endif
\if :{?runtime_role}
\else
  \set runtime_role wp_runtime
\endif

SELECT EXISTS (
  SELECT 1 FROM pg_roles WHERE rolname = :'migration_role'
) AS migration_role_exists \gset
SELECT EXISTS (
  SELECT 1 FROM pg_roles WHERE rolname = :'runtime_role'
) AS runtime_role_exists \gset

\if :migration_role_exists
\else
  \echo 'Missing migration role. Create it in the RDS console, then retry.'
  \quit 3
\endif
\if :runtime_role_exists
\else
  \echo 'Missing runtime role. Create it in the RDS console, then retry.'
  \quit 3
\endif

SELECT :'migration_role' <> :'runtime_role' AS roles_are_distinct \gset
\if :roles_are_distinct
\else
  \echo 'migration_role and runtime_role must be different LOGIN roles.'
  \quit 3
\endif

BEGIN;

ALTER ROLE :"migration_role"
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
ALTER ROLE :"runtime_role"
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;

-- PUBLIC cannot retain CREATE because a role cannot have an explicit DENY that
-- overrides PUBLIC. The migration owner is the only application role allowed
-- to create schema objects.
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM :"runtime_role";
ALTER SCHEMA public OWNER TO :"migration_role";
GRANT USAGE, CREATE ON SCHEMA public TO :"migration_role";
GRANT USAGE ON SCHEMA public TO :"runtime_role";
GRANT CONNECT ON DATABASE :"DBNAME" TO :"migration_role", :"runtime_role";

-- Move all non-extension application objects to the role used by Alembic.
-- psql's \gexec safely executes the identifier-quoted statements generated by
-- format(); no role name is interpolated into a dollar-quoted PL/pgSQL body.
SELECT format(
  'ALTER TABLE %I.%I OWNER TO %I',
  namespace.nspname,
  relation.relname,
  :'migration_role'
)
FROM pg_class AS relation
JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
LEFT JOIN pg_depend AS dependency
  ON dependency.classid = 'pg_class'::regclass
 AND dependency.objid = relation.oid
 AND dependency.deptype = 'e'
WHERE namespace.nspname = 'public'
  AND relation.relkind IN ('r', 'p')
  AND dependency.objid IS NULL
ORDER BY relation.relname
\gexec

SELECT format(
  'ALTER SEQUENCE %I.%I OWNER TO %I',
  namespace.nspname,
  relation.relname,
  :'migration_role'
)
FROM pg_class AS relation
JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
LEFT JOIN pg_depend AS dependency
  ON dependency.classid = 'pg_class'::regclass
 AND dependency.objid = relation.oid
 AND dependency.deptype = 'e'
WHERE namespace.nspname = 'public'
  AND relation.relkind = 'S'
  AND dependency.objid IS NULL
ORDER BY relation.relname
\gexec

SELECT format(
  'ALTER VIEW %I.%I OWNER TO %I',
  namespace.nspname,
  relation.relname,
  :'migration_role'
)
FROM pg_class AS relation
JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
LEFT JOIN pg_depend AS dependency
  ON dependency.classid = 'pg_class'::regclass
 AND dependency.objid = relation.oid
 AND dependency.deptype = 'e'
WHERE namespace.nspname = 'public'
  AND relation.relkind = 'v'
  AND dependency.objid IS NULL
ORDER BY relation.relname
\gexec

SELECT format(
  'ALTER MATERIALIZED VIEW %I.%I OWNER TO %I',
  namespace.nspname,
  relation.relname,
  :'migration_role'
)
FROM pg_class AS relation
JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
LEFT JOIN pg_depend AS dependency
  ON dependency.classid = 'pg_class'::regclass
 AND dependency.objid = relation.oid
 AND dependency.deptype = 'e'
WHERE namespace.nspname = 'public'
  AND relation.relkind = 'm'
  AND dependency.objid IS NULL
ORDER BY relation.relname
\gexec

SELECT format(
  'ALTER FUNCTION %I.%I(%s) OWNER TO %I',
  namespace.nspname,
  procedure.proname,
  pg_get_function_identity_arguments(procedure.oid),
  :'migration_role'
)
FROM pg_proc AS procedure
JOIN pg_namespace AS namespace ON namespace.oid = procedure.pronamespace
LEFT JOIN pg_depend AS dependency
  ON dependency.classid = 'pg_proc'::regclass
 AND dependency.objid = procedure.oid
 AND dependency.deptype = 'e'
WHERE namespace.nspname = 'public'
  AND dependency.objid IS NULL
ORDER BY procedure.proname, pg_get_function_identity_arguments(procedure.oid)
\gexec

-- Alembic owns future objects. Runtime gets a broad baseline only while API
-- replicas remain disabled; harden-runtime.sql removes dangerous privileges
-- immediately after each successful migration and before API/worker rollout.
GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA public TO :"runtime_role";
GRANT USAGE, SELECT
  ON ALL SEQUENCES IN SCHEMA public TO :"runtime_role";
ALTER DEFAULT PRIVILEGES FOR ROLE :"migration_role" IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"runtime_role";
ALTER DEFAULT PRIVILEGES FOR ROLE :"migration_role" IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO :"runtime_role";
ALTER DEFAULT PRIVILEGES FOR ROLE :"migration_role" IN SCHEMA public
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

COMMIT;

\echo 'Role ownership bootstrap complete. Keep API/worker disabled.'
\echo 'Run Alembic as the migration owner, then run harden-runtime.sql.'
